
const MAIN_INPUT_CHANGE = 'MAIN_INPUT_CHANGE'

const REQUET_FLIGHTS_PENDING = 'REQUET_FLIGHTS_PENDING'
const REQUET_FLIGHTS_SUCCESS = 'REQUET_FLIGHTS_SUCCESS'
const REQUET_FLIGHTS_FAIL = 'REQUET_FLIGHTS_FAIL'

const REQUET_COUNTIERS_PENDING = 'REQUET_FLIGHTS_PENDING'
const REQUET_COUNTIERS_SUCCESS = 'REQUET_FLIGHTS_SUCCESS'
const REQUET_COUNTIERS_FAIL = 'REQUET_FLIGHTS_FAIL'



module.exports = {
    MAIN_INPUT_CHANGE,
    REQUET_FLIGHTS_FAIL,
    REQUET_FLIGHTS_PENDING,
    REQUET_FLIGHTS_SUCCESS,
    REQUET_COUNTIERS_FAIL,
    REQUET_COUNTIERS_PENDING,
    REQUET_COUNTIERS_SUCCESS
}